media:
  input: assets/images
  output: /assets/images

content:
  - name: skill_categories
    label: Skill Categories
    type: collection
    path: _skill_categories
    filename: '{fields.name}.md'
    fields:
    - name: name
      label: Name
      type: string
    - name: order
      label: Order
      type: number
  
  - name: skills
    label: Skills
    type: collection
    path: _skills
    filename: '{fields.name}.md'
    fields:
      - name: name
        label: Name
        type: string
      - name: icon
        label: Icon
        type: image
      - name: skill_category
        label: Category
        type: reference
        options:
          collection: skill_categories
          multiple: false
          value: '{fields.name}'
          label: '{fields.name}'
  
  - name: projects
    label: Projects
    type: collection
    path: _projects
    filename: '{fields.title}.md'
    view:
      fields: [title, description, date]
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: text
      - name: date
        label: Date
        type: date
      - name: skills
        label: Skills
        type: reference
        options:
          collection: skills
          multiple: true
          value: '{fields.name}'
          label: '{fields.name}'
      - name: link
        label: Link
        type: string
      - name: screenshot
        label: Screenshot
        type: image
      - name: body
        label: Body
        type: rich-text
  
  - name: config
    label: Site settings
    type: file
    path: _data/settings.yml
    fields: 
      - name: title
        label: Site title
        type: string
      - name: description
        label: Site description
        type: string
      - name: profile_image
        label: Profile Image
        type: image