title: Kaven Liu 
description: Entry-level software engineer 
baseurl: "" 
url: "https://reios0.github.io"
timezone: America/Toronto
collections: 
  skills: 
    output: false
  projects: 
    output: true 
    permalink: /projects/:name/ 
defaults: 
  - scope: 
      path: "" 
      type: projects 
    values: 
      layout: project